export const mockStats = {
  totalCars: 18,
  availableCars: 11,
  featuredCars: 4,
  totalLeads: 27,
  newLeads: 8,
};

export const mockCars = [
  {
    id: "car-1",
    slug: "porsche-911-carrera-s-2021",
    brand: "Porsche",
    model: "911 Carrera S",
    version: "992",
    price: 154900,
    year: 2021,
    mileage_km: 18500,
    fuel: "Gasolina",
    transmission: "Automatico",
    power_hp: 450,
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
    category: "Performance",
    description: "Coupe em estado irrepreensivel, historico conhecido e configuracao muito equilibrada.",
    shortDescription: "Configuracao premium, baixo uso e historico documentado.",
    gallery: [],
    highlight: "Unidade de referencia para cliente que procura desportivo moderno com uso contido.",
    monthlyLabel: "Financiamento disponivel",
    featured: true,
    status: "available",
    specs: {
      engine: "3.0 Boxer",
      drivetrain: "RWD",
      acceleration: "3.7s",
      exterior: "Cinza",
      interior: "Preto",
      location: "Coimbra",
    },
    created_at: "2026-04-09T12:00:00Z",
  },
  {
    id: "car-2",
    slug: "bmw-m3-competition-2022",
    brand: "BMW",
    model: "M3 Competition",
    version: "",
    price: 99900,
    year: 2022,
    mileage_km: 22000,
    fuel: "Gasolina",
    transmission: "Automatico",
    power_hp: 510,
    image: "",
    category: "Performance",
    description: "Sedan de performance com configuracao focada em estrada e imagem forte.",
    shortDescription: "Performance moderna com equipamento completo.",
    gallery: [],
    highlight: "Modelo com muita procura e excelente visibilidade no stock.",
    monthlyLabel: "",
    featured: false,
    status: "reserved",
    specs: {
      engine: "3.0 Twin Turbo",
      drivetrain: "RWD",
      acceleration: "3.9s",
      exterior: "Preto",
      interior: "Preto",
      location: "Coimbra",
    },
    created_at: "2026-04-08T12:00:00Z",
  },
  {
    id: "car-3",
    slug: "land-rover-defender-110-2023",
    brand: "Land Rover",
    model: "Defender 110",
    version: "P400",
    price: 87900,
    year: 2023,
    mileage_km: 9000,
    fuel: "Gasolina",
    transmission: "Automatico",
    power_hp: 400,
    image: "",
    category: "SUV",
    description: "SUV premium com imagem forte e aptidoes familiares.",
    shortDescription: "SUV premium com baixa quilometragem.",
    gallery: [],
    highlight: "Boa unidade de margem e excelente efeito vitrina.",
    monthlyLabel: "",
    featured: true,
    status: "draft",
    specs: {
      engine: "3.0",
      drivetrain: "AWD",
      acceleration: "6.0s",
      exterior: "Verde",
      interior: "Camel",
      location: "Coimbra",
    },
    created_at: "2026-04-07T12:00:00Z",
  },
];

export const mockLeads = [
  {
    id: "lead-1",
    form_type: "contact",
    name: "Joao Costa",
    email: "joao@email.pt",
    phone: "+351912345678",
    brand: null,
    model: null,
    year: null,
    mileage_km: null,
    message: "Queria marcar visita para o 911 ainda esta semana.",
    status: "new",
    created_at: "2026-04-09T16:00:00Z",
  },
  {
    id: "lead-2",
    form_type: "sell",
    name: "Ana Martins",
    email: "ana@email.pt",
    phone: "+351934567890",
    brand: "Mercedes-Benz",
    model: "C63 AMG",
    year: 2019,
    mileage_km: 41000,
    message: "Pretendo avaliacao e proposta de retoma.",
    status: "contacted",
    created_at: "2026-04-09T10:30:00Z",
  },
  {
    id: "lead-3",
    form_type: "contact",
    name: "Pedro Silva",
    email: "pedro@email.pt",
    phone: null,
    brand: null,
    model: null,
    year: null,
    mileage_km: null,
    message: "Gostava de saber se aceitam financiamento para o M3.",
    status: "closed",
    created_at: "2026-04-08T18:45:00Z",
  },
];
